### ISSUE TITLE
Testing w/ dask-cudf

### ISSUE THREAD

**Issue by randerzander** [dask-contrib/dask-sql#155]
Hello,

I'm experimenting with dask-sql using [GPU DataFrames](https://github.com/rapidsai/cudf) instead of Pandas DataFrames.

Some basic functionality works, but there seem to be type discrepancies for floating point math. It's likely that this is a cudf/pandas or cudf/dask compatibility problem, but I'm opening here for initial discussion.

cc @quasiben

```
from dask_sql import Context
import cudf, dask_cudf

c = Context()

df = cudf.DataFrame()
df['id'] = [0, 1, 2]
df['val'] = [0, 1, 2]

c.create_table('test', dask_cudf.from_cudf(df, npartitions=2))

# basic test works
c.sql("select * from test").compute()
	id	val
0	0	0
1	1	1
2	2	2

# basic addition works
c.sql("select val+10 from test").compute()
"test"."val" + 10
0	10
1	11
2	12

# division fails
c.sql("select val/10 from test").compute()
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-58-827590261210> in <module>
----> 1 c.sql("select val/10 from test").compute()

~/conda/envs/rapids/lib/python3.8/site-packages/dask_sql/context.py in sql(self, sql, return_futures)
    378         rel, select_names, _ = self._get_ral(sql)
    379 
--> 380         dc = RelConverter.convert(rel, context=self)
    381 
    382         if dc is None:

~/conda/envs/rapids/lib/python3.8/site-packages/dask_sql/physical/rel/convert.py in convert(cls, rel, context)
     54             f"Processing REL {rel} using {plugin_instance.__class__.__name__}..."
     55         )
---> 56         df = plugin_instance.convert(rel, context=context)
     57         logger.debug(f"Processed REL {rel} into {LoggableDataFrame(df)}")
     58         return df

~/conda/envs/rapids/lib/python3.8/site-packages/dask_sql/physical/rel/logical/project.py in convert(self, rel, context)
     70         cc = self.fix_column_to_row_type(cc, rel.getRowType())
     71         dc = DataContainer(df, cc)
---> 72         dc = self.fix_dtype_to_row_type(dc, rel.getRowType())
     73         return dc

~/conda/envs/rapids/lib/python3.8/site-packages/dask_sql/physical/rel/base.py in fix_dtype_to_row_type(dc, row_type)
    107             field_name = cc.get_backend_by_frontend_index(index)
    108 
--> 109             df = cast_column_type(df, field_name, expected_type)
    110 
    111         return DataContainer(df, dc.column_container)

~/conda/envs/rapids/lib/python3.8/site-packages/dask_sql/mappings.py in cast_column_type(df, column_name, expected_type)
    276 
    277     logger.debug(f"Need to cast {column_name} from {current_type} to {expected_type}")
--> 278     df[column_name] = df[column_name].astype(expected_type)
    279 
    280     return df

~/conda/envs/rapids/lib/python3.8/site-packages/dask/dataframe/core.py in astype(self, dtype)
   2665             meta = self._meta_nonempty.astype(dtype)
   2666         else:
-> 2667             meta = self._meta.astype(dtype)
   2668         if hasattr(dtype, "items"):
   2669             set_unknown = [

~/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py in astype(self, dtype, copy, errors)
   3446         except Exception as e:
   3447             if errors == "raise":
-> 3448                 raise e
   3449             elif errors == "warn":
   3450                 import traceback

~/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py in astype(self, dtype, copy, errors)
   3438             return self.copy(deep=copy)
   3439         try:
-> 3440             data = self._column.astype(dtype)
   3441 
   3442             return self._copy_construct(

~/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py in astype(self, dtype, **kwargs)
   1052         elif is_decimal_dtype(dtype):
   1053             return self.as_decimal_column(dtype, **kwargs)
-> 1054         elif np.issubdtype(dtype, np.datetime64):
   1055             return self.as_datetime_column(dtype, **kwargs)
   1056         elif np.issubdtype(dtype, np.timedelta64):

~/conda/envs/rapids/lib/python3.8/site-packages/numpy/core/numerictypes.py in issubdtype(arg1, arg2)
    386     """
    387     if not issubclass_(arg1, generic):
--> 388         arg1 = dtype(arg1).type
    389     if not issubclass_(arg2, generic):
    390         arg2 = dtype(arg2).type

TypeError: Cannot interpret 'Int64Dtype()' as a data type
```

**Comment by kkraus14** [comment]
This is a bug on cudf's side in not handling Pandas extension types. We can address this.

**Comment by nils-braun** [comment]
Very interesting and thanks for trying it out!
And also thanks to @kkraus14 for jumping in (I think also dask has seen similar problems in the past https://github.com/dask/dask/issues/7156). 

Maybe now to your question behind all that: can/will dask-sql support dask-cudf :-)
I have two concerns here, one is more technical and one more general.
Technical, there are currently many references to "pandas"-dask in dask-sql (e.g. many scalar functions reference dask.array methods etc.) That would be possible to fix of course, but unfortunately, would not be a nice plug-and-play (due to the plugin mechanism however, I think it should be doable without too many code changes).
That however brings us to the more general concern I have: there is of course also the very nice blazingSQL that supports SQL on GPUs. Now I am honestly not an expert in cudf, but from my very naive high-level view, I wouldn't see a benefit in having two tools to support the same use case (if I am totally wrong and the two use cases are different, please do tell me as I am really not into this topic :-)). Have you tried blazingSQL? Did you find anything that isn't supported in blazingSQL (maybe we can port it from dask-sql to blazingSQL) or were you just experimenting out of fun (which I totally understand ;-))?

**Comment by randerzander** [comment]
Thanks for the response, Nils.

I had seen tweets about this project and was merely experimenting. I use BlazingSQL frequently, and was interested in performance and supported SQL syntax differences.

**Comment by nils-braun** [comment]
There is some significant work in this direction now. @sarahyurick has started some PRs (e.g. #211 and #207) to make dask-cudf work with dask-sql. Maybe @sarahyurick can you quickly summarize the current status (what works, what does not work so far) and where we could help you?

**Comment by sarahyurick** [comment]
Absolutely! With both #211 and #207, these basic queries work: select, select distinct, where, and, or, not, order by, null checks, min, max, count, avg, sum, like, in, between, groupby, having, exists, case, and operators. 

However, we are not able to merge #207 into dask-sql (since it causes one of Nils' tests to fail), which is needed to make groupby aggregations work with cuDF. We currently have the issue open on the cuDF side: https://github.com/rapidsai/cudf/issues/9017 but are leaving #207 open for benchmarking purposes. Maybe @randerzander could comment on the types of queries being used there.

As far as I'm aware, any other issues that we are encountering are from the cuDF or Dask side. Thanks for all of your help so far, Nils!

**Comment by jdye64** [comment]
Could this issue be closed now?

**Comment by VibhuJawa** [comment]
Closing this as we support this now.
