### ISSUE TITLE
[FEA] 0.4 Release ?

### ISSUE THREAD

**Issue by quasiben** [dask-contrib/dask-sql#257]
It's been awhile since dask-sql has done a release.  With the new committers on the team,  I was curious if you all would be interested in testing out dask-sql's release process

cc @rajagurunath @galipremsagar @charlesbluca 

I suspect @rajagurunath would like to see #231 go in before any release

**Comment by rajagurunath** [comment]
For sure, It's really a great idea, Lot of good work was added since the last release !!!. Please let me know if something needs to be done from my end. (And Apologies for being late).

> I suspect @rajagurunath would like to see #231 go in before any release

For sure @quasiben, I have already started looking into this PR, Feeling somewhat less confident in the testing part, Happy to incorporate  Feedbacks/suggestions from @charlesbluca. May we will try to incorporate the rich/ textual features in upcoming releases.  (Actually planning to come up with UI Layer for dask-sql for different interfaces like browser (using streamlit), terminal (using rich), jupyter-lab plugins, a very small step towards that https://github.com/rajagurunath/dask-sql-workbench, happy to know everyone's thoughts on this :) ).


> Something else I had been thinking about (but isn't pertinent with this release) is if we wanted to move to CalVer to match up with Dask/Distributed, since it seems like some of the work we're doing currently is bound to development in Dask.

I also like the CalVer idea !! 👍

**Comment by charlesbluca** [comment]
With #231 merged in, I think we're in a pretty good place to do another release. @rajagurunath @quasiben how does a release in the next couple days sound?

**Comment by charlesbluca** [comment]
Closing this now that 0.4.0 is out - note that we'll probably want to do a minor release once #294 or another solution for #297 is merged in
