### ISSUE TITLE
[ENH] substr() not supported in dask-sql

### ISSUE THREAD

**Issue by DaceT** [dask-contrib/dask-sql#258]
**Is your feature request related to a problem? Please describe.**
I'm working on porting a large set of queries from another engine to dask-sql. I see that I can update the queries to use "substring" instead, but it would be nice if users didn't have to.

**Describe the solution you'd like**
Can we have substr() supported in dask-sql in the same way that substring() is?

**Describe alternatives you've considered**
substring() works in dask-sql not substr(). However, we do not want to alter the sql files by changing substr() to substring()

**Additional context**
Here's an example query I'd like to be able to run:
      `import cudf 
      from dask_sql import Context
      
      dc = Context()
      
      df = cudf.DataFrame({'s_c': ['ATX', 'LAX', 'SFO'], 's_d':['38714','37206','38714'], 
                           'd_d':['1900-01-01','1900-01-04','2199-12-28']})
      dc.create_table('my_table', df) 
      
     
      query = """
                select substr(s_c,1,30)
                from
                 (select s_c
                  from my_table
                  where s_d = d_d           
                  group by s_c)
              """
      
      print(dc.sql(query).compute())`

**Comment by ayushdg** [comment]
@DaceT Thanks for raising this issue! If you get a chance could you try `dc.explain(query)` and post the output from that command. Trying to evaluate if it's just something that's unsupported on the python side, or if the calcite parser doesn't support `substr` because of the grammar syntax supported today.

**Comment by DaceT** [comment]
@ayushdg oops, thanks for the correction!

**Comment by jdye64** [comment]
I can knock this one out

**Comment by ayushdg** [comment]
After some debugging I was able to confirm that the `substr` method is enabled via the Postresql operator table as mentioned in https://github.com/dask-contrib/dask-sql/issues/258#issuecomment-944440271. 

I'm suspecting that the issue with parsing was around case sensitivity since `SUBSTR` worked and was able to confirm that `substr` also works after setting the config `dask.sql.identifier.case.sensitive` to `false`. I'll open a pr to add tests for `substr` before closing.

**Comment by jdye64** [comment]
Ahh yeah that makes complete sense. Good find!

**Comment by randerzander** [comment]
This was resolved now that we can configure case sensitivity
