### ISSUE TITLE
[BUG] Selecting based on dates unexpectedly returns no results.

### ISSUE THREAD

**Issue by ChrisJar** [dask-contrib/dask-sql#296]
**What happened**:
When selecting rows based on a set of dates, dask-sql returns no results even though there are matches

**Minimal Complete Verifiable Example**:

For example:
```python
import dask.dataframe as dd
import pandas as pd
from dask_sql import Context

df = pd.DataFrame({'d_date':["2001-08-01", "2001-08-02", "2001-08-03"], 'val':[1,2,3]})
ddf = dd.from_pandas(df, npartitions=1)

c = Context()
c.create_table("df", ddf)

query = "SELECT val, d_date FROM df WHERE CAST(d_date as date) IN (date '2001-08-01', date '2001-08-03')"
c.sql(query).compute()
```
returns:
```
Empty DataFrame
Columns: [val, d_date]
Index: []
```
This also occurs when the input column is cast to datetime:
```python
import dask.dataframe as dd
import pandas as pd
from dask_sql import Context

df = pd.DataFrame({'d_date':["2001-08-01", "2001-08-02", "2001-08-03"], 'val':[1,2,3]})
df['d_date'] = pd.to_datetime(df['d_date'], format='%Y-%m-%d')
ddf = dd.from_pandas(df, npartitions=1)

c = Context()
c.create_table("df", ddf)

query = "SELECT val, d_date FROM df WHERE CAST(d_date as date) IN (date '2001-08-01', date '2001-08-03')"
c.sql(query).compute()
```
However: this does not occur when using GPU dataframes. For example:
```python
import dask_cudf
import cudf
from dask_sql import Context

df = cudf.DataFrame({'d_date':["2001-08-01", "2001-08-02", "2001-08-03"], 'val':[1,2,3]})
ddf = dask_cudf.from_cudf(df, npartitions=1)

c = Context()
c.create_table("df", ddf)

query = "SELECT val, d_date FROM df WHERE CAST(d_date as date) IN (date '2001-08-01', date '2001-08-03')"
c.sql(query).compute()
```
returns
```
   val      d_date
0    1  2001-08-01
2    3  2001-08-03
```

**Environment**:

- dask-sql version: 0.3.10
- Python version: 3.8
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): Source

**Comment by rajagurunath** [comment]
Hi @ChrisJar,

Thanks for writing this detailed Description and easy-to-reproduce code snippets, really appreciate it!

The Bug seems to occur due to the mismatch in date format between the two operands, i.e we are comparing the dask series (%Y-%m-%d) with DateTime literal value ("%Y-%m-%d %H:%M:%S"). Even though we are explicitly cast the operands. 

My initial attempt at this Bug was here: https://github.com/rajagurunath/dask-sql/commit/61cbca951bb4b62639ffcba43034f1dac392e24e

Happy to know everyone's thoughts on this! :)

**Comment by charlesbluca** [comment]
Is there any reason why we can't just cast the date scalars to `pd.Timestamps` instead of `datetime.datetime`?

```diff
diff --git a/dask_sql/mappings.py b/dask_sql/mappings.py
index 5df6a42..4479495 100644
--- a/dask_sql/mappings.py
+++ b/dask_sql/mappings.py
@@ -160,9 +160,7 @@ def sql_to_python_value(sql_type: str, literal_value: Any) -> Any:
         tz = literal_value.getTimeZone().getID()
         assert str(tz) == "UTC", "The code can currently only handle UTC timezones"
 
-        dt = datetime.fromtimestamp(
-            int(literal_value.getTimeInMillis()) / 1000, timezone.utc
-        )
+        dt = pd.Timestamp(literal_value.getTimeInMillis(), unit="ms")
 
         return dt
```

This seems to give us matching types between scalar `DATE` objects and the results of a `CAST(... as date)` operation, which seems to resolve things both these queries and those described in [this comment](https://github.com/dask-contrib/dask-sql/pull/298/files#issuecomment-971764672); I can investigate more on why cuDF behaves differently from Pandas here, though a naive guess is that cuDF casts `datetime` objects to `pd.Timestamps` where Pandas does not

**Comment by charlesbluca** [comment]
Looks like that guess was correct:

```python
import datetime

import cudf
import pandas as pd

dt = datetime.datetime.fromtimestamp(996710400.0, datetime.timezone.utc)

df = pd.DataFrame({'d_date':["2001-08-01", "2001-08-02", "2001-08-03"], 'val':[1,2,3]})
df['d_date'] = pd.to_datetime(df['d_date'], format='%Y-%m-%d')
expect = df[df['d_date'] == dt]
# Empty DataFrame
# Columns: [d_date, val]
# Index: []

gdf = cudf.DataFrame({'d_date':["2001-08-01", "2001-08-02", "2001-08-03"], 'val':[1,2,3]})
gdf['d_date'] = cudf.to_datetime(gdf['d_date'], format='%Y-%m-%d')
got = gdf[gdf['d_date'] == dt]
#       d_date  val
# 1 2001-08-02    2
```

In that case, perhaps the documentation on this belongs in cuDF? cc @quasiben
