### ISSUE TITLE
[ENH] Changing `java` command to build option

### ISSUE THREAD

**Issue by jakirkham** [dask-contrib/dask-sql#400]
**Is your feature request related to a problem? Please describe.**

Currently Dask-SQL has a non-standard build option, `java`, which is used to build the Java components. Though this is presumably something we would want to do during the package build. This would also make it easier to use with other Python build tools familiar with standard Python build options (like `build_ext`).

**Describe the solution you'd like**

Would be nice to have the Java build step implemented as a `build_ext` subclass with an option to build the Java component. This would allow for a standard command to be used, `build_ext`, which other Python build tools are familiar with.

**Describe alternatives you've considered**

Another [command]( https://github.com/pypa/setuptools/tree/main/setuptools/command ) could be used other than `build_ext` if there's an appropriate one (though `build_ext` sounds right as it is used to compile non-Python code).

One could parse args manually in `setup.py` and use them. This is a bit hacky, but could be simple to implement.

**Additional context**

Came from looking at how to build the Java components using `pip`.

**Comment by charlesbluca** [comment]
Yeah this is something I wanted to do in https://github.com/dask-contrib/dask-sql/pull/396 when we swapped to using `versioneer.get_cmdclass()` so that package build would be consolidated like it was when we explicitly defined the `build_py` command:

https://github.com/dask-contrib/dask-sql/blob/8d6480017b14acc8becd41cb93ca9c8dc72bd887/setup.py#L45-L51

I think `build_ext` seems like the most sensible command to implement the Java step (though I haven't looked into the hoops of making a subclass); happy to sync up and look deeper into this 🙂

**Comment by jakirkham** [comment]
Sounds good. Happy to chat 🙂

Think [this doc]( https://setuptools.pypa.io/en/latest/deprecated/distutils/apiref.html#creating-a-new-distutils-command ) may help fill in some details of how this might work. Though would use [the setuptools equivalent]( https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html ) (they are still working on porting things over/cleaning it up).
